scripts/guest: increases memory on guest
This change prevents the guest machine on running without meemory during
the patchtest execution; in particular avoiding ExpansionErrors when Bitbake
is used.

This change ensures the following error doesn't happen:
ERROR: ExpansionError during parsing /home/patchtest-user/openembedded-core/
meta/recipes-extended/images/core-image-testmaster.bb
...
exception OSError: [Errno 12] Cannot allocate memory

Signed-off-by: Daniela Plascencia <daniela.plascencia@linux.intel.com>